--- #YAML:1.0
name:                Crypt-PBC
version:             0.853
abstract:            OO interface for the Stanford PBC library
license:             ~
author:              
    - Paul Miller <jettero@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Math::BigInt:                  0
    Math::BigInt::GMP:             0
    MIME::Base64:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
