---
name: Crypt-PBC
version: 0.7.20.3.4.18
author: []
abstract: OO interface for the Stanford PBC library
license: lgpl
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  MIME::Base64: 0
  Math::BigInt: 0
  Math::BigInt::GMP: 0
  version: 0.75
build_requires:
  ExtUtils::CBuilder: 0
provides:
  Crypt::PBC:
    file: PBC.pm
    version: 0.7.20.3.4.18
  Crypt::PBC::Element:
    file: PBC.pm
  Crypt::PBC::Pairing:
    file: PBC.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
